version: 2
jobs:
  build:
    docker:
      - image: alpine
    working_directory: ~/devops-kompose
    steps:
      - checkout
      - run:
          name: helm-github-pages
          command: wget -O - https://raw.githubusercontent.com/int128/helm-github-pages/master/publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: int128/helm-charts
